# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1024, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    background-color: rgba(255, 255, 255, 1);\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"}")
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 2, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.timeEdit = QtWidgets.QTimeEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeEdit.sizePolicy().hasHeightForWidth())
        self.timeEdit.setSizePolicy(sizePolicy)
        self.timeEdit.setReadOnly(True)
        self.timeEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.timeEdit.setObjectName("timeEdit")
        self.timeEdit.setDisplayFormat("hh:mm:ss")
        self.timeEdit.setStyleSheet("font-size: 18px;")
        self.verticalLayout.addWidget(self.timeEdit)
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit.sizePolicy().hasHeightForWidth())
        self.dateEdit.setSizePolicy(sizePolicy)
        self.dateEdit.setReadOnly(True)
        self.dateEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateEdit.setDate(QtCore.QDate(2000, 1, 1))
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit.setDisplayFormat("dd MMMM yyyy")
        self.dateEdit.setStyleSheet("font-size: 18px;")
        self.verticalLayout.addWidget(self.dateEdit)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.infoLbl = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.infoLbl.setFont(font)
        self.infoLbl.setStyleSheet("QLabel {\n"
"    background-color: rgba(255, 255, 255, 1);\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    padding: 8px\n"
"}")
        self.infoLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.infoLbl.setObjectName("infoLbl")
        self.horizontalLayout.addWidget(self.infoLbl)
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.countDownLbl = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countDownLbl.sizePolicy().hasHeightForWidth())
        self.countDownLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.countDownLbl.setFont(font)
        self.countDownLbl.setStyleSheet("QLabel{\n"
"    background-color: rgba(255, 255, 255, 1);\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"}")
        self.countDownLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.countDownLbl.setObjectName("countDownLbl")
        self.horizontalLayout_2.addWidget(self.countDownLbl)
        spacerItem2 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 1)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.chatgptLbl = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.chatgptLbl.setFont(font)
        self.chatgptLbl.setStyleSheet("QLabel {\n"
"    background-color: rgba(255, 255, 255, 0.9);\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    padding: 8px;\n"
"}")
        self.chatgptLbl.setText("")
        self.chatgptLbl.setTextFormat(QtCore.Qt.PlainText)
        self.chatgptLbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.chatgptLbl.setWordWrap(True)
        self.chatgptLbl.setObjectName("chatgptLbl")
        self.gridLayout_2.addWidget(self.chatgptLbl, 1, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pauseBtn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.pauseBtn.setFont(font)
        self.pauseBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pauseBtn.setStyleSheet("QPushButton {\n"
"    border: 1px solid gray; \n"
"    border-radius: 10px;     \n"
"    padding: 5px;\n"
"    background-color: rgb(225, 225, 225);\n"
"}\n"
"")
        self.pauseBtn.setObjectName("pauseBtn")
        self.gridLayout.addWidget(self.pauseBtn, 0, 2, 1, 1)
        self.resetBtn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.resetBtn.setFont(font)
        self.resetBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.resetBtn.setStyleSheet("QPushButton {\n"
"    border: 1px solid gray; \n"
"    border-radius: 10px;     \n"
"    padding: 5px;\n"
"    background-color: rgb(225, 225, 225);\n"
"}\n"
"")
        self.resetBtn.setObjectName("resetBtn")
        self.gridLayout.addWidget(self.resetBtn, 1, 2, 1, 1)
        self.countdownEdit = QtWidgets.QTimeEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countdownEdit.sizePolicy().hasHeightForWidth())
        self.countdownEdit.setSizePolicy(sizePolicy)
        self.countdownEdit.setObjectName("countdownEdit")
        self.countdownEdit.setDisplayFormat("hh:mm:ss")
        self.gridLayout.addWidget(self.countdownEdit, 0, 0, 1, 1)
        self.startBtn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startBtn.sizePolicy().hasHeightForWidth())
        self.startBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.startBtn.setFont(font)
        self.startBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.startBtn.setStyleSheet("QPushButton {\n"
"    border: 1px solid gray; \n"
"    border-radius: 10px;     \n"
"    padding: 5px;\n"
"    background-color: rgb(225, 225, 225);\n"
"}\n"
"")
        self.startBtn.setObjectName("startBtn")
        self.gridLayout.addWidget(self.startBtn, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.cameraLbl = QtWidgets.QLabel(self.centralwidget)
        self.cameraLbl.setStyleSheet("QLabel{\n"
"    background-color: rgba(255, 255, 255, 1);\n"
"    border: 1px solid brown;\n"
"    border-radius: 5px;\n"
"}")
        self.cameraLbl.setText("")
        self.cameraLbl.setObjectName("cameraLbl")
        self.cameraLbl.setScaledContents(True)
        self.gridLayout_2.addWidget(self.cameraLbl, 1, 0, 2, 1)
        self.gridLayout_2.setColumnStretch(0, 2)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.gridLayout_2.setRowStretch(1, 14)
        self.gridLayout_2.setRowStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        self.menuHome = QtWidgets.QMenu(self.menubar)
        self.menuHome.setObjectName("menuHome")
        self.menuSchedule = QtWidgets.QMenu(self.menubar)
        self.menuSchedule.setObjectName("menuSchedule")
        MainWindow.setMenuBar(self.menubar)
        self.actionnew = QtWidgets.QAction(MainWindow)
        self.actionnew.setObjectName("actionnew")
        self.menubar.addAction(self.menuHome.menuAction())
        self.menubar.addAction(self.menuSchedule.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.infoLbl.setText(_translate("MainWindow", "User detected: 0"))
        self.countDownLbl.setText(_translate("MainWindow", "00:00:00"))
        self.pauseBtn.setText(_translate("MainWindow", "Pause"))
        self.resetBtn.setText(_translate("MainWindow", "Reset"))
        self.startBtn.setText(_translate("MainWindow", "START"))
        self.menuHome.setTitle(_translate("MainWindow", "Home"))
        self.menuSchedule.setTitle(_translate("MainWindow", "Schedule"))
        self.actionnew.setText(_translate("MainWindow", "new"))
