# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1024, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.timeEdit = QtWidgets.QTimeEdit(self.centralwidget)
        self.timeEdit.setReadOnly(True)
        self.timeEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.timeEdit.setObjectName("timeEdit")
        self.gridLayout_2.addWidget(self.timeEdit, 0, 0, 1, 1)
        self.setTimeBtn = QtWidgets.QPushButton(self.centralwidget)
        self.setTimeBtn.setStyleSheet("QPushButton {\n"
"    border: 1px solid gray; \n"
"    border-radius: 10px;     \n"
"    padding: 5px;\n"
"    background-color: rgb(225, 225, 225);\n"
"}\n"
"")
        self.setTimeBtn.setObjectName("setTimeBtn")
        self.gridLayout_2.addWidget(self.setTimeBtn, 0, 1, 1, 1)
        self.infoLbl = QtWidgets.QLabel(self.centralwidget)
        self.infoLbl.setStyleSheet("QLabel {\n"
"    background-color: rgba(255, 255, 255, 1);\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    padding: 8px\n"
"}")
        self.infoLbl.setText("")
        self.infoLbl.setObjectName("infoLbl")
        self.gridLayout_2.addWidget(self.infoLbl, 0, 2, 2, 1)
        self.countDownLbl = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.countDownLbl.setFont(font)
        self.countDownLbl.setStyleSheet("QLabel{\n"
"    background-color: rgba(255, 255, 255, 1);\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"}")
        self.countDownLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.countDownLbl.setObjectName("countDownLbl")
        self.gridLayout_2.addWidget(self.countDownLbl, 0, 3, 2, 1)
        self.setCountDownBtn = QtWidgets.QPushButton(self.centralwidget)
        self.setCountDownBtn.setStyleSheet("QPushButton {\n"
"    border: 1px solid gray; \n"
"    border-radius: 10px;     \n"
"    padding: 5px;\n"
"    background-color: rgb(225, 225, 225);\n"
"}\n"
"")
        self.setCountDownBtn.setObjectName("setCountDownBtn")
        self.gridLayout_2.addWidget(self.setCountDownBtn, 0, 4, 2, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setReadOnly(True)
        self.dateEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateEdit.setDate(QtCore.QDate(2000, 1, 1))
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout_2.addWidget(self.dateEdit, 1, 0, 1, 1)
        self.setDateBtn = QtWidgets.QPushButton(self.centralwidget)
        self.setDateBtn.setStyleSheet("QPushButton {\n"
"    border: 1px solid gray; \n"
"    border-radius: 10px;     \n"
"    padding: 5px;\n"
"    background-color: rgb(225, 225, 225);\n"
"}\n"
"")
        self.setDateBtn.setObjectName("setDateBtn")
        self.gridLayout_2.addWidget(self.setDateBtn, 1, 1, 1, 1)
        self.cameraLbl = QtWidgets.QLabel(self.centralwidget)
        self.cameraLbl.setStyleSheet("QLabel{\n"
"    background-color: rgba(255, 255, 255, 1);\n"
"    border: 2px solid black;\n"
"    border-radius: 5px;\n"
"}")
        self.cameraLbl.setText("")
        self.cameraLbl.setObjectName("cameraLbl")
        self.cameraLbl.setScaledContents(True)
        self.gridLayout_2.addWidget(self.cameraLbl, 2, 0, 2, 3)
        self.chatGPTLbl = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.chatGPTLbl.setFont(font)
        self.chatGPTLbl.setStyleSheet("QLabel {\n"
"    background-color: rgba(255, 255, 255, 0.9);\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    padding: 8px;\n"
"}")
        self.chatGPTLbl.setText("")
        self.chatGPTLbl.setTextFormat(QtCore.Qt.PlainText)
        self.chatGPTLbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.chatGPTLbl.setWordWrap(True)
        self.chatGPTLbl.setObjectName("chatGPTLbl")
        self.gridLayout_2.addWidget(self.chatGPTLbl, 2, 3, 1, 2)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    background-color: rgba(255, 255, 255, 1);\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 3, 3, 1, 2)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.gridLayout_2.setColumnStretch(2, 3)
        self.gridLayout_2.setColumnStretch(3, 1)
        self.gridLayout_2.setColumnStretch(4, 1)
        self.gridLayout_2.setRowStretch(2, 12)
        self.gridLayout_2.setRowStretch(3, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        self.menuHome = QtWidgets.QMenu(self.menubar)
        self.menuHome.setObjectName("menuHome")
        self.menuSchedule = QtWidgets.QMenu(self.menubar)
        self.menuSchedule.setObjectName("menuSchedule")
        MainWindow.setMenuBar(self.menubar)
        self.actionnew = QtWidgets.QAction(MainWindow)
        self.actionnew.setObjectName("actionnew")
        self.menubar.addAction(self.menuHome.menuAction())
        self.menubar.addAction(self.menuSchedule.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.setTimeBtn.setText(_translate("MainWindow", "Set Time"))
        self.countDownLbl.setText(_translate("MainWindow", "00:00"))
        self.setCountDownBtn.setText(_translate("MainWindow", "Set Time"))
        self.setDateBtn.setText(_translate("MainWindow", "Set Date"))
        self.menuHome.setTitle(_translate("MainWindow", "Home"))
        self.menuSchedule.setTitle(_translate("MainWindow", "Schedule"))
        self.actionnew.setText(_translate("MainWindow", "new"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
